services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=pdes
    depends_on:
      - db
    volumes:
      - .:/usr/src/apps
      - /usr/src/apps/node_modules
      
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pdes
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: